//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkuManager.UI.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkuManager.UI.Resources.Strings.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installiert alle Sku-WoW-Addons/Skripte und deren Abhängigkeiten, welche im eingestellten Manifest enthalten sind. ähnelt.
        /// </summary>
        public static string mainwindow_action_install_description {
            get {
                return ResourceManager.GetString("mainwindow_action_install_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installieren ähnelt.
        /// </summary>
        public static string mainwindow_action_install_title {
            get {
                return ResourceManager.GetString("mainwindow_action_install_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisiere alle Sku-WoW-Addons und dazugehörige skripts.
        ///Zu nächst wird nach updates für die Addons/Skripts gesucht, die im Manifest festgelegt wurden. Dann wird, falls gewünscht das Update durchgeführt.
        ///
        ///Bitte beachte:
        ///Es wird nur nach Updates für die Addons/Skripts und deren abhänigkeiten gesucht, welche im Manifest vermerkt sind. ähnelt.
        /// </summary>
        public static string mainwindow_action_update_description {
            get {
                return ResourceManager.GetString("mainwindow_action_update_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisieren ähnelt.
        /// </summary>
        public static string mainwindow_action_update_title {
            get {
                return ResourceManager.GetString("mainwindow_action_update_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfetext zur ausgewählten aktion ähnelt.
        /// </summary>
        public static string mainwindow_actionDescription_accessibilityDescription {
            get {
                return ResourceManager.GetString("mainwindow_actionDescription_accessibilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Aktion ausgewählt. 
        ///Wähle erst eine Aktion im Dropdown aus, dann erscheint hier ein Hilfetext zu dieser Aktion. ähnelt.
        /// </summary>
        public static string mainwindow_actionDescription_placeholder {
            get {
                return ResourceManager.GetString("mainwindow_actionDescription_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle eine Aktion aus. Du kannst mit TAB zum nächsten Feld wechseln, dort findest Du zur ausgewählten Aktion einen Hilfetext. Bestätige die Auswahl mit dem Schalter namens &quot;OK&quot;. ähnelt.
        /// </summary>
        public static string mainwindow_actionPicker_accessibilityHint {
            get {
                return ResourceManager.GetString("mainwindow_actionPicker_accessibilityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle die Aktion aus, die du ausführen möchtest. ähnelt.
        /// </summary>
        public static string mainwindow_instructionsLabel {
            get {
                return ResourceManager.GetString("mainwindow_instructionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnet ein fenster, in dem unter anderem die Dokumentation des SkuManagers geöffnet werden kann. ähnelt.
        /// </summary>
        public static string mainwindow_moreButton_accessibilityHint {
            get {
                return ResourceManager.GetString("mainwindow_moreButton_accessibilityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mehr ähnelt.
        /// </summary>
        public static string mainwindow_moreButton_title {
            get {
                return ResourceManager.GetString("mainwindow_moreButton_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über SkuManager ähnelt.
        /// </summary>
        public static string mainwindow_moreMenu_item_about {
            get {
                return ResourceManager.GetString("mainwindow_moreMenu_item_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterstütze das Sku-Projekt ähnelt.
        /// </summary>
        public static string mainwindow_moreMenu_item_donate {
            get {
                return ResourceManager.GetString("mainwindow_moreMenu_item_donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gehe zum Github-Repository des Sku-Addons ähnelt.
        /// </summary>
        public static string mainwindow_moreMenu_item_sku_repo {
            get {
                return ResourceManager.GetString("mainwindow_moreMenu_item_sku-repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gehe zur offiziellen Webseite des Sku-Addons ähnelt.
        /// </summary>
        public static string mainwindow_moreMenu_item_sku_website {
            get {
                return ResourceManager.GetString("mainwindow_moreMenu_item_sku-website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffne die Dokumentation des SkuManagers ähnelt.
        /// </summary>
        public static string mainwindow_moreMenu_item_skumanager_doc {
            get {
                return ResourceManager.GetString("mainwindow_moreMenu_item_skumanager-doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gehe zum Github-Repository des SkuManagers ähnelt.
        /// </summary>
        public static string mainwindow_moreMenu_item_skumanager_repo {
            get {
                return ResourceManager.GetString("mainwindow_moreMenu_item_skumanager-repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Besuche uns in Discord ähnelt.
        /// </summary>
        public static string mainwindow_moreMenuItem_sku_discord {
            get {
                return ResourceManager.GetString("mainwindow_moreMenuItem_sku-discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Führt die in diesem Fenster ausgewählte Aktion aus. ähnelt.
        /// </summary>
        public static string mainwindow_okButton_accessibilityHint {
            get {
                return ResourceManager.GetString("mainwindow_okButton_accessibilityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string mainwindow_okButton_title {
            get {
                return ResourceManager.GetString("mainwindow_okButton_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnet die Einstellungen. ähnelt.
        /// </summary>
        public static string mainwindow_optionsButton_accessibilityHint {
            get {
                return ResourceManager.GetString("mainwindow_optionsButton_accessibilityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string mainwindow_optionsButton_title {
            get {
                return ResourceManager.GetString("mainwindow_optionsButton_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SkuManager - Was möchtest du machen? ähnelt.
        /// </summary>
        public static string mainwindow_title {
            get {
                return ResourceManager.GetString("mainwindow_title", resourceCulture);
            }
        }
    }
}
