//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkuManager.UI.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkuManager.UI.Resources.Strings.LocalizableStrings", typeof(LocalizableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähle den interface-Ordner deiner World of Warcraft-Classic installation. ähnelt.
        /// </summary>
        public static string folderDialog_wowInterfacePath_description {
            get {
                return ResourceManager.GetString("folderDialog_wowInterfacePath_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle den Ordner deiner wow_menu installation aus. ähnelt.
        /// </summary>
        public static string folderDialog_wowMenuPath_description {
            get {
                return ResourceManager.GetString("folderDialog_wowMenuPath_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installiert alle Sku-WoW-Addons/Skripte und deren Abhängigkeiten, welche im eingestellten Manifest enthalten sind. ähnelt.
        /// </summary>
        public static string mainwindow_action_install_description {
            get {
                return ResourceManager.GetString("mainwindow_action_install_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installieren ähnelt.
        /// </summary>
        public static string mainwindow_action_install_title {
            get {
                return ResourceManager.GetString("mainwindow_action_install_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisiere alle Sku-WoW-Addons und dazugehörige skripts.
        ///Zu nächst wird nach updates für die Addons/Skripts gesucht, die im Manifest festgelegt wurden. Dann wird, falls gewünscht das Update durchgeführt.
        ///
        ///Bitte beachte:
        ///Es wird nur nach Updates für die Addons/Skripts und deren abhänigkeiten gesucht, welche im Manifest vermerkt sind. ähnelt.
        /// </summary>
        public static string mainwindow_action_update_description {
            get {
                return ResourceManager.GetString("mainwindow_action_update_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisieren ähnelt.
        /// </summary>
        public static string mainwindow_action_update_title {
            get {
                return ResourceManager.GetString("mainwindow_action_update_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfetext zur ausgewählten aktion ähnelt.
        /// </summary>
        public static string mainwindow_actionDescription_accessibilityDescription {
            get {
                return ResourceManager.GetString("mainwindow_actionDescription_accessibilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Aktion ausgewählt. 
        ///Wähle erst eine Aktion im Dropdown aus, dann erscheint hier ein Hilfetext zu dieser Aktion. ähnelt.
        /// </summary>
        public static string mainwindow_actionDescription_placeholder {
            get {
                return ResourceManager.GetString("mainwindow_actionDescription_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle eine Aktion aus. Du kannst mit TAB zum nächsten Feld wechseln, dort findest Du zur ausgewählten Aktion einen Hilfetext. Bestätige die Auswahl mit dem Schalter namens &quot;OK&quot;. ähnelt.
        /// </summary>
        public static string mainwindow_actionPicker_accessibilityHint {
            get {
                return ResourceManager.GetString("mainwindow_actionPicker_accessibilityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle die Aktion aus, die du ausführen möchtest. ähnelt.
        /// </summary>
        public static string mainwindow_instructionsLabel {
            get {
                return ResourceManager.GetString("mainwindow_instructionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnet ein fenster, in dem unter anderem die Dokumentation des SkuManagers geöffnet werden kann. ähnelt.
        /// </summary>
        public static string mainwindow_moreButton_accessibilityHint {
            get {
                return ResourceManager.GetString("mainwindow_moreButton_accessibilityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mehr ähnelt.
        /// </summary>
        public static string mainwindow_moreButton_title {
            get {
                return ResourceManager.GetString("mainwindow_moreButton_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über SkuManager ähnelt.
        /// </summary>
        public static string mainwindow_moreMenu_item_about {
            get {
                return ResourceManager.GetString("mainwindow_moreMenu_item_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterstütze das Sku-Projekt ähnelt.
        /// </summary>
        public static string mainwindow_moreMenu_item_donate {
            get {
                return ResourceManager.GetString("mainwindow_moreMenu_item_donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gehe zum Github-Repository des Sku-Addons ähnelt.
        /// </summary>
        public static string mainwindow_moreMenu_item_sku_repo {
            get {
                return ResourceManager.GetString("mainwindow_moreMenu_item_sku-repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gehe zur offiziellen Webseite des Sku-Addons ähnelt.
        /// </summary>
        public static string mainwindow_moreMenu_item_sku_website {
            get {
                return ResourceManager.GetString("mainwindow_moreMenu_item_sku-website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffne die Dokumentation des SkuManagers ähnelt.
        /// </summary>
        public static string mainwindow_moreMenu_item_skumanager_doc {
            get {
                return ResourceManager.GetString("mainwindow_moreMenu_item_skumanager-doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gehe zum Github-Repository des SkuManagers ähnelt.
        /// </summary>
        public static string mainwindow_moreMenu_item_skumanager_repo {
            get {
                return ResourceManager.GetString("mainwindow_moreMenu_item_skumanager-repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Besuche uns in Discord ähnelt.
        /// </summary>
        public static string mainwindow_moreMenuItem_sku_discord {
            get {
                return ResourceManager.GetString("mainwindow_moreMenuItem_sku-discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Führt die in diesem Fenster ausgewählte Aktion aus. ähnelt.
        /// </summary>
        public static string mainwindow_okButton_accessibilityHint {
            get {
                return ResourceManager.GetString("mainwindow_okButton_accessibilityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string mainwindow_okButton_title {
            get {
                return ResourceManager.GetString("mainwindow_okButton_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnet die Einstellungen. ähnelt.
        /// </summary>
        public static string mainwindow_optionsButton_accessibilityHint {
            get {
                return ResourceManager.GetString("mainwindow_optionsButton_accessibilityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string mainwindow_optionsButton_title {
            get {
                return ResourceManager.GetString("mainwindow_optionsButton_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SkuManager - Was möchtest du machen? ähnelt.
        /// </summary>
        public static string mainwindow_title {
            get {
                return ResourceManager.GetString("mainwindow_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Einstellungen sind nicht valide! ähnelt.
        /// </summary>
        public static string settings_error_caption {
            get {
                return ResourceManager.GetString("settings_error_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Einstellungen sind nicht valide.
        ///Bitte Überprüfe nocheinmal deine Einstellungen und versuche es dann erneut.
        ///Grund:
        ///{0} ähnelt.
        /// </summary>
        public static string settings_error_mainMessage {
            get {
                return ResourceManager.GetString("settings_error_mainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Addon-Manifest wurde nicht konfiguriert. ähnelt.
        /// </summary>
        public static string settings_error_manifestIsNull {
            get {
                return ResourceManager.GetString("settings_error_manifestIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Pfad zum Interface-Ordner deiner WoW-Classic installation endet nicht mit &quot;interface&quot;. Bitte Überprüfe ob der Pfad korrekt ist. ähnelt.
        /// </summary>
        public static string settings_error_wowInterfacePathEndsNotWithInterface {
            get {
                return ResourceManager.GetString("settings_error_wowInterfacePathEndsNotWithInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Pfad zum Interface-Ordner deiner WoW-Classic installation wurde nicht konfiguriert. ähnelt.
        /// </summary>
        public static string settings_error_wowInterfacePathIsNull {
            get {
                return ResourceManager.GetString("settings_error_wowInterfacePathIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Installationspfad des wow_menu&apos;s wurde nicht konfiguriert. ähnelt.
        /// </summary>
        public static string settings_error_wowMenuPathIsNull {
            get {
                return ResourceManager.GetString("settings_error_wowMenuPathIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließt dieses Fenster und kehrt zum Hauptfenster zurück. Dabei werden vorgenommene Änderungen verworfen. ähnelt.
        /// </summary>
        public static string settingsWindow_cancelButton_accessibilityHint {
            get {
                return ResourceManager.GetString("settingsWindow_cancelButton_accessibilityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string settingsWindow_cancelButton_title {
            get {
                return ResourceManager.GetString("settingsWindow_cancelButton_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle hier ein Addon-Manifest aus. Diese werden verwendet, um zu Steuern welche Addons installiert/aktualisiert werden sollen. ähnelt.
        /// </summary>
        public static string settingsWindow_manifestPicker_instructionsLabel {
            get {
                return ResourceManager.GetString("settingsWindow_manifestPicker_instructionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichert die Einstellungen und kehrt zum Hauptfenster zurück. ähnelt.
        /// </summary>
        public static string settingsWindow_okButton_accessibilityHint {
            get {
                return ResourceManager.GetString("settingsWindow_okButton_accessibilityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string settingsWindow_okButton_title {
            get {
                return ResourceManager.GetString("settingsWindow_okButton_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skumanager - Einstellungen ähnelt.
        /// </summary>
        public static string settingswindow_title {
            get {
                return ResourceManager.GetString("settingswindow_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pfad zum Interface-Ordner deiner World of Warcraft Classic installation.
        ///Benutze den Schalter &quot;Ordner suchen&quot; um einen Dialog zum auswählen des Ordners zu öffnen. Du kannst in der schreibgeschützten Textbox den Pfad überprüfen. Er muss auf &quot;interface&quot; enden. ähnelt.
        /// </summary>
        public static string settingsWindow_wowInterfacePath_instructionsLabel {
            get {
                return ResourceManager.GetString("settingsWindow_wowInterfacePath_instructionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnet einen Ordner-Suchen Dialog in dem du den geforderten Ordner suchen kannst. Bestätige die auswahl dann mit OK. ähnelt.
        /// </summary>
        public static string settingsWindow_wowInterfacePath_searchButton_accessibilityHint {
            get {
                return ResourceManager.GetString("settingsWindow_wowInterfacePath_searchButton_accessibilityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner suchen ähnelt.
        /// </summary>
        public static string settingsWindow_wowInterfacePath_searchButton_title {
            get {
                return ResourceManager.GetString("settingsWindow_wowInterfacePath_searchButton_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle hier den Pfad zu deiner wow_menu installation. 
        ///Bitte beachte das in den Ordner der von dir ausgewählt wird, die Dateien von wow_menu zu finden sein sollten. D.h. im Ordner den Du auswählst sollten die .ahk-Dateien usw. vorhanden sein. 
        ///Falls Du das wow_menu erst installieren musst, werden die Dateien in dem Ordner abgelegt, den Du hier auswählst.
        ///Du kannst in der schreibgeschützten Textbox den Pfad überprüfen. ähnelt.
        /// </summary>
        public static string settingsWindow_wowMenuPath_instructionsLabel {
            get {
                return ResourceManager.GetString("settingsWindow_wowMenuPath_instructionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnet einen Ordner-Suchen Dialog in dem du den geforderten Ordner suchen kannst. Bestätige die auswahl dann mit OK. ähnelt.
        /// </summary>
        public static string settingsWindow_wowMenuPath_searchButton_accessibilityHint {
            get {
                return ResourceManager.GetString("settingsWindow_wowMenuPath_searchButton_accessibilityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner suchen ähnelt.
        /// </summary>
        public static string settingsWindow_wowMenuPath_searchButton_title {
            get {
                return ResourceManager.GetString("settingsWindow_wowMenuPath_searchButton_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutze TAB um zu dem Schalter zu springen, mit dem Du den geforderten Ordner suchen kannst. ähnelt.
        /// </summary>
        public static string settingsWindow_wowMenuPath_textbox_accessibilityHint {
            get {
                return ResourceManager.GetString("settingsWindow_wowMenuPath_textbox_accessibilityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutze TAB um zu dem Schalter zu springen, mit dem Du den geforderten Ordner suchen kannst. ähnelt.
        /// </summary>
        public static string settingsWindowwowInterfacePath_textBox_accessibilityHint {
            get {
                return ResourceManager.GetString("settingsWindowwowInterfacePath_textBox_accessibilityHint", resourceCulture);
            }
        }
    }
}
